feat: implement disabling logging api
athakor/java-storage pull request #12
Opened 2020-06-22 16:40 UTC by athakor

2020-06-22 17:05 UTC, dmitry-fa requested changes
I'm not sure that `disableLogging()` is a good method for a builder class.
Just supporting `setLogging(null)` will be enough, I think

2020-06-23 09:58 UTC, athakor commented
@dmitry-fa According to the given api doc, this method seems more appropriate than to set null.

2020-06-23 10:37 UTC, dmitry-fa commented
@athakor, 
there is a well-known software design pattern called 'Builder'. This pattern is widely used in Google libraries. The typical usage is:    
`updated =  obj.toBuilder().setX(x).setY(y).setZ(z).build()`
 The problem of the current implementation that `setLogging(null)` is not handled correctly. 
Your change fixes that problem. That's great. 
But the fix brings also inconsistency with a generic approach, which is not necessary. 

If you don't believe me, you can submit a public PR. But I will raise the same question there.

2020-06-23 10:42 UTC, dmitry-fa commented
> 
> @dmitry-fa According to the given [api doc](https://cloud.google.com/storage/docs/access-logs#disabling), this method seems more appropriate than to set null.
> 

Quoting an [example ](https://cloud.google.com/storage/docs/access-logs#json-api_2) from the doc you mentioned:

```
PATCH /example-bucket?logging HTTP/1.1
Host: storage.googleapis.com
{
 "logging": null
}
```
Disabling logging is implemented as setting the logging property to null

2020-06-23 10:46 UTC, athakor commented
> > @dmitry-fa According to the given [api doc](https://cloud.google.com/storage/docs/access-logs#disabling), this method seems more appropriate than to set null.
> 
> Quoting an [example ](https://cloud.google.com/storage/docs/access-logs#json-api_2) from the doc you mentioned:
> 
> ```
> PATCH /example-bucket?logging HTTP/1.1
> Host: storage.googleapis.com
> {
>  "logging": null
> }
> ```
> 
> Disabling logging is implemented as setting the logging property to null

okay thanks for the feedback will did the change as per  you.

2020-06-23 13:21 UTC, athakor commented
@dmitry-fa PTAL

2020-06-23 14:27 UTC, dmitry-fa requested changes
Overall looks good, please fix to avoid duplication in the ITStorage test

2020-06-23 14:27 UTC, dmitry-fa commented on google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
> +  }
You duplicated the code of an existed tests, that is not good. 
Could you extend the existing test to check that set loggin to null have an effect, please

2020-06-23 14:27 UTC, dmitry-fa commented on google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
> +            .build();
Nit: do you need all these settings here? Would it make sense to minimize invocation of setters on  the builder, just to make the code more compact.

2020-06-23 15:55 UTC, athakor commented
@dmitry-fa both the comments have been addressed PTAL

2020-06-23 16:05 UTC, closed without merging